name: 'Problem Filter'
description: 'Filter out warning or error messages output to stdout using specific conditions'
inputs:
  run:
    description: 'shell command to execute'
    required: true
  type:
    description: 'Problem-matcher type'
    required: true
    default: 'dotnet'
  files:
    description: 'JSON array of files to print'
    required: false
outputs:
  errors:
    description: 'Error messages during execution of shell'
runs:
  using: 'node12'
  main: 'dist/index.js'
